apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  type: NodePort
  selector:
    app: cart-service
  ports:
  - name: http
    protocol: TCP
    port: 8093